///////////////////////////////////////////////////////////
//  EAEditionTypes.cs
//  Implementation of the Enumeration EAEditionTypes
//  Generated by Enterprise Architect
//  Created on:      22-Nov-2020 14:16:23
//  Original author: alto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace MDD4All.EAFacade.DataModels.Contracts {
	public enum EAEditionTypes : int {

		piLite,
		piDesktop,
		piProfessional,
		piCorporate,
		piBusiness,
		piSystemEng,
		piUltimate

	}//end EAEditionTypes

}//end namespace Contracts